Repository mi-gan-zi/FE-MiGanZi, pull requests merged in 2023-07, with the labels that each got.

#90 Fix & Refactor: 로그아웃 토큰이슈 문제 해결 & reIssue 재정의
  .gitignore
  package.json
  src/components/myPage/Container.tsx
  src/components/myPage/Header.tsx
  src/components/signin/NicknameComponent.tsx
  src/components/signin/SignInComponent.tsx
  src/index.tsx
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
  src/pages/TestDetail.tsx
  src/repository/LocalTokenRepository.ts
  src/services/apis/boardService.ts
  src/services/apis/mianziService.ts
  src/services/axiosClient/axios.ts
  yarn.lock
Labels: 🚀 Todo

#94 Refactor: 콘솔로고 삭제 | 만료기간 로직 수정
  src/repository/LocalTokenRepository.ts
  src/services/apis/miganziService.ts
  src/services/axiosClient/axios.ts
Labels: hotfix

#100 Refactor: axiosClient를 더 간편하게 사용하도록 수정
  src/components/create/Description.tsx
  src/hooks/useAuth.ts
  src/pages/Create.tsx
  src/repository/LocalTokenRepository.ts
  src/services/apis/miganziService.ts
  src/shared/Router.tsx
Labels: documentation

#103 Refactor: axiosClient get, post, delete, put 함수 제거
  src/components/signin/SignInComponent.tsx
  src/hooks/useAuth.ts
  src/pages/Create.tsx
  src/pages/MyPage.tsx
  src/services/apis/miganziService.ts
  src/services/axiosClient/axios.ts
  src/shared/Router.tsx
Labels: refactor
